/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartPageFrame.java
 *
 * Created on 08/04/2011, 02:03:15 م
 */

package OurPackage;
import OurPackage.Query;
import OurPackage.JavaAccess;
import OurPackage.ManageCat;
import OurPackage.Map;
import OurPackage.MyTweets;
import OurPackage.Results;
import OurPackage.TwitterClass;
import javax.swing.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 *
 * @author pc
 */
public class StartPageFrame extends javax.swing.JFrame {

    /** Creates new form StartPageFrame */
    public StartPageFrame() {
        initComponents();
       QueryObj.setLookAndFeel();
       //ShowPanel.add(new ManageCat());
       showTwitterPage();
       TwitterObj.Trends();
       showTrends();
       setLocationRelativeTo(null);
        cat.showCat();
                 setLookAndFeel();
                 
                 //look.setLookAndFeel();
                 //cat.setLookAndFeel();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MangeCategoriesButton = new javax.swing.JButton();
        QueryButton = new javax.swing.JButton();
        MyTweets = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ShowPanel = new javax.swing.JTabbedPane();
        TrendsPanel = new javax.swing.JPanel();
        TrendsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(199, 218, 242));

        jPanel2.setBackground(new java.awt.Color(85, 153, 187));
        jPanel2.setName("jPanel2"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(85, 153, 187));
        jPanel1.setName("jPanel1"); // NOI18N

        MangeCategoriesButton.setText("Mange Categories");
        MangeCategoriesButton.setName("MangeCategoriesButton"); // NOI18N
        MangeCategoriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MangeCategoriesButtonMousePressed(evt);
            }
        });

        QueryButton.setText("Query");
        QueryButton.setName("QueryButton"); // NOI18N
        QueryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QueryButtonMousePressed(evt);
            }
        });

        MyTweets.setText("Saved Data");
        MyTweets.setName("MyTweets"); // NOI18N
        MyTweets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MyTweetsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QueryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(MyTweets, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(MangeCategoriesButton))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MangeCategoriesButton, MyTweets, QueryButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(QueryButton)
                .addGap(18, 18, 18)
                .addComponent(MyTweets)
                .addGap(18, 18, 18)
                .addComponent(MangeCategoriesButton)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MangeCategoriesButton, MyTweets, QueryButton});

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sherif\\Desktop\\project\\isalast.png")); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setName("jLabel1"); // NOI18N

        ShowPanel.setBackground(new java.awt.Color(255, 255, 255));
        ShowPanel.setName("ShowPanel"); // NOI18N

        TrendsPanel.setBackground(new java.awt.Color(34, 68, 102));
        TrendsPanel.setName("TrendsPanel"); // NOI18N

        TrendsLabel.setForeground(new java.awt.Color(221, 238, 255));
        TrendsLabel.setName("TrendsLabel"); // NOI18N

        javax.swing.GroupLayout TrendsPanelLayout = new javax.swing.GroupLayout(TrendsPanel);
        TrendsPanel.setLayout(TrendsPanelLayout);
        TrendsPanelLayout.setHorizontalGroup(
            TrendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrendsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrendsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 2929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrendsPanelLayout.setVerticalGroup(
            TrendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrendsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TrendsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2074, Short.MAX_VALUE)
                    .addComponent(TrendsPanel, 0, 2074, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrendsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MangeCategoriesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MangeCategoriesButtonMousePressed
        showMangeCategoriesPage();        // TODO add your handling code here:
    }//GEN-LAST:event_MangeCategoriesButtonMousePressed

    private void QueryButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueryButtonMousePressed
        showTwitterPage();
        
    }//GEN-LAST:event_QueryButtonMousePressed

    private void MyTweetsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTweetsMousePressed
    showMyTweetsPage();
    }//GEN-LAST:event_MyTweetsMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPageFrame().setVisible(true);
                
            }
        });
    }
    
    
  public void setLookAndFeel()
    {
        try {
		UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (UnsupportedLookAndFeelException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MangeCategoriesButton;
    private javax.swing.JButton MyTweets;
    private javax.swing.JButton QueryButton;
    public static javax.swing.JTabbedPane ShowPanel;
    private javax.swing.JLabel TrendsLabel;
    private javax.swing.JPanel TrendsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
//Query QueryPanel = new Query();
    //ManageCat CatPanel = new ManageCat();
    //Trends TrendsPanel = new Trends();
    private void showTwitterPage() {
       ShowPanel.removeAll();
       ShowPanel.add(new Query());
       ShowPanel.setTitleAt(0, "Twitter");
    }

    private void showMyTweetsPage() {
       ShowPanel.removeAll();
       ShowPanel.add(new MyTweets());
      ShowPanel.setTitleAt(0, "My Tweets");
    }

   

    private void showMangeCategoriesPage() {
        ShowPanel.removeAll();
       ShowPanel.add(new ManageCat());
       ShowPanel.setTitleAt(0, "Manage Categories");
    }
    
    private void showTrends() {
        
        //TrendsLabel.setLocation(TrendsLabel.getLocation().x,TrendsLabel.getLocation().y);
        
        Timer timer = new Timer (100, new ActionListener() { public void actionPerformed(ActionEvent e) {
           
                TrendsLabel.setText(TwitterObj.getTrends());
                //TrendsLabel.setLocation(TrendsLabel.getSize().width-1000,TrendsLabel.getLocation().y);
                if(TrendsLabel.getLocation().x > -3000)
                    TrendsLabel.setLocation(TrendsLabel.getLocation().x-5,TrendsLabel.getLocation().y);
                else
                {
                    TrendsLabel.setLocation(TrendsLabel.getSize().width-1000,TrendsLabel.getLocation().y);
                }
            
        }
        });
        timer.start();
    }
    
    ManageCat cat = new ManageCat();
    MyTweets look = new MyTweets();
    Query QueryObj = new Query();
    TwitterClass TwitterObj = new TwitterClass();
}
